const GET_GAMES = "GET_GAMES"
const GET_GENRES = "GET_GENRES"
const SET_PAGE = "SET_PAGE"

const FILTER = "FILTER"

const ORIGIN = "ORIGIN"

const ORDER = "ORDER"

const SEARCH = "SEARCH"

const ORDER_RATING = "ORDER_RATING"

const INCREASE_TARGET_PAGE = "INCREASE_TARGET_PAGE"



export {
    GET_GAMES, GET_GENRES, SET_PAGE,
    FILTER, ORIGIN, ORDER, SEARCH, 
    ORDER_RATING, INCREASE_TARGET_PAGE
};